#CREATE DATABASE BUILDHEYGOMS;

USE BUILDHEYGOMS;

CREATE TABLE CLASS (
    CLASS_ID 			VARCHAR(20) 	PRIMARY KEY,
    CLASS_NM 			VARCHAR(50) 	NOT NULL,
	TRAINER_ID 			VARCHAR(20) 	NOT NULL,
	CREATE_CLASS_DT 	TIMESTAMP,
	ACTIVEACCOUNT_YN 	VARCHAR(200)
);

