#CREATE DATABASE BUILDHEYGOMS;

USE BUILDHEYGOMS;

CREATE TABLE JOIN_REQUEST (
    JOIN_REQUEST_ID 	VARCHAR(20) 	PRIMARY KEY,
    MEMBER_ID 			VARCHAR(20) 	NOT NULL,
	TRAINER_ID 			VARCHAR(20) 	NOT NULL,
    INTRODUCTION		VARCHAR(200)
);

