#CREATE DATABASE BUILDHEYGOMS;

USE BUILDHEYGOMS;

CREATE TABLE TRAINER (
    TRAINER_ID 			VARCHAR(20) PRIMARY KEY,
    PASSWD 				VARCHAR(200) NOT NULL,
    TRAINER_NM 			VARCHAR(50)  NOT NULL,
	SEX 				CHAR(1)  	 NOT NULL,
	BIRTH_DT 			VARCHAR(100) NOT NULL, 
	HP 					VARCHAR(100)  NOT NULL,
	EMAIL 				VARCHAR(30)  NOT NULL,
	ADDRESS 			VARCHAR(200),
	BUSINESS_LOCATION	VARCHAR(200),
	CONNECTED_MEMBER	VARCHAR(50),
	CAREER_BOOK			VARCHAR(200),
	JOIN_DT 			TIMESTAMP,
    INTRODUCTION		VARCHAR(200),
	ACTIVEACCOUNT_YN 	VARCHAR(200)
);

